version: '3'
services:
  hello-go:
    image: dsbonafedev/hello-go:latest
    container_name: hellogo
    build:
      context: .
      dockerfile: Dockerfile.prod
    networks:
      - gonet

networks:
  gonet:
    driver: bridge
